version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      # - pip install -r requirements.txt # Uncomment if you have dependencies
  build:
    commands:
      - echo Build started on `date`
      - echo Building the SAM application...
      - sam build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging and Deploying...
      # Note: This assumes the CodeBuild role has permissions to CloudFormation and S3
      # You might want to use 'sam package' and 'sam deploy' separately or just output the template for CodePipeline to deploy
      # For a simple "just deploy" pipeline:
      - sam deploy --stack-name my-cicd-lambda-stack --capabilities CAPABILITY_IAM --resolve-s3 --no-fail-on-empty-changeset

artifacts:
  files:
    - template.yaml
    - output-template.yaml
